########################################################################
# This is the setup script for the MAterials Simulation Toolkit
#   machine-learning module (MASTML)
# Creator: Tam Mayeshiba
# Maintainer: Robert Max Williams
# Last updated: 2018-06-20
#  _________________________________
# / No one knows where the original \
# \ setup.py came from.             /
#  ---------------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
########################################################################

from __future__ import print_function
import sys
from setuptools import setup, find_packages

###Python version check
#print "Python version detected: %s" % sys.version_info
if sys.version_info[0] < 3:
    print('Python Version %d.%d.%d found' % (sys.version_info[0], sys.version_info[1], sys.version_info[2]))
    print('Python version >= 3 needed!')
    sys.exit(0)

#print("Python version 3.6.6 is REQUIRED")
#print("Check with `python --version`")

# One of the techniques from https://packaging.python.org/guides/single-sourcing-package-version/
verstr = "unknown"
try:
    verstr = open("VERSION", "rt").read().strip()
except EnvironmentError:
    pass # Okay, there is no version file.

setup(
    name="mastml", # TODO  should this be MAST-ML?
    #packages=find_packages(),
    packages=['mastml', 'mastml.legos'],
    data_files=[('tests', ['tests/csv/example_data.csv'],
                 ['tests/conf/example_input.conf']),
                 ('magpie', ['magpie/AtomicNumber.table']),
                 ('magpie', ['magpie/AtomicRadii.table']),
                ('magpie', ['magpie/AtomicVolume.table']),
                ('magpie', ['magpie/AtomicWeight.table']),
                ('magpie', ['magpie/BCCefflatcnt.table']),
                ('magpie', ['magpie/BCCenergy_pa.table']),
                ('magpie', ['magpie/BCCenergydiff']),
                ('magpie', ['magpie/BCCfermi.table']),
                ('magpie', ['magpie/BCCmagmom.table']),
                ('magpie', ['magpie/BCCvolume_pa.table']),
                ('magpie', ['magpie/BCCvolume_padiff.table']),
                ('magpie', ['magpie/BoilingT.table']),
                ('magpie', ['magpie/BulkModulus.table']),
                ('magpie', ['magpie/Column.table']),
                ('magpie', ['magpie/CovalentRadii.table']),
                ('magpie', ['magpie/CovalentRadius.table']),
                ('magpie', ['magpie/Density.table']),
                ('magpie', ['magpie/ElasticModulus.table']),
                ('magpie', ['magpie/ElectricalConductivity.table']),
                ('magpie', ['magpie/ElectronAffinity.table']),
                ('magpie', ['magpie/Electronegativity.table']),
                ('magpie', ['magpie/FirstIonizationEnergy.table']),
                ('magpie', ['magpie/Group.table']),
                ('magpie', ['magpie/GSbandgap.table']),
                ('magpie', ['magpie/GSenergy_pa.table']),
                ('magpie', ['magpie/GSestBCClatcnt.table']),
                ('magpie', ['magpie/GSestFCClatcnt.table']),
                ('magpie', ['magpie/GSmagmom.table']),
                ('magpie', ['magpie/GSvolume_pa.table']),
                ('magpie', ['magpie/HeatCapacityMass.table']),
                ('magpie', ['magpie/HeatCapacityMolar.table']),
                ('magpie', ['magpie/HeatFusion.table']),
                ('magpie', ['magpie/HeatVaporization.table']),
                ('magpie', ['magpie/HHIp.table']),
                ('magpie', ['magpie/HHIr.table']),
                ('magpie', ['magpie/ICSDVolume.table']),
                ('magpie', ['magpie/IonicRadii.table']),
                ('magpie', ['magpie/IonizationEnergy.table']),
                ('magpie', ['magpie/IsAlkali.table']),
                ('magpie', ['magpie/IsAlkalineEarth.table']),
                ('magpie', ['magpie/IsBCC.table']),
                ('magpie', ['magpie/IsBoron.table']),
                ('magpie', ['magpie/IsCarbon.table']),
                ('magpie', ['magpie/IsChalcogen.table']),
                ('magpie', ['magpie/IsDBlock.table']),
                ('magpie', ['magpie/IsFBlock.table']),
                ('magpie', ['magpie/IsFCC.table']),
                ('magpie', ['magpie/IsHalogen.table']),
                ('magpie', ['magpie/IsHexagonal.table']),
                ('magpie', ['magpie/IsMetal.table']),
                ('magpie', ['magpie/IsMetalloid.table']),
                ('magpie', ['magpie/IsMonoclinic.table']),
                ('magpie', ['magpie/IsNobleGas.table']),
                ('magpie', ['magpie/IsNonmetal.table']),
                ('magpie', ['magpie/IsOrthorhombic.table']),
                ('magpie', ['magpie/IsPnictide.table']),
                ('magpie', ['magpie/IsRareEarth.table']),
                ('magpie', ['magpie/IsRhombohedral.table']),
                ('magpie', ['magpie/IsSimpleCubic.table']),
                ('magpie', ['magpie/IsTetragonal.table']),
                ('magpie', ['magpie/IsTransitionMetal.table']),
                ('magpie', ['magpie/MeltingT.table']),
                ('magpie', ['magpie/MendeleevNumber.table']),
                ('magpie', ['magpie/MiracleRadius.table']),
                ('magpie', ['magpie/n_ws ^ third.table']),
                ('magpie', ['magpie/NdUnfilled.table']),
                ('magpie', ['magpie/NdValence.table']),
                ('magpie', ['magpie/NfUnfilled.table']),
                ('magpie', ['magpie/NfValence.table']),
                ('magpie', ['magpie/NpUnfilled.table']),
                ('magpie', ['magpie/NpValence.table']),
                ('magpie', ['magpie/NsUnfilled.table']),
                ('magpie', ['magpie/NsValence.table']),
                ('magpie', ['magpie/Number.table']),
                ('magpie', ['magpie/NUnfilled.table']),
                ('magpie', ['magpie/NValance.table']),
                ('magpie', ['magpie/OxidationStates.table']),
                ('magpie', ['magpie/Period.table']),
                ('magpie', ['magpie/phi.table']),
                ('magpie', ['magpie/Polarizability.table']),
                ('magpie', ['magpie/Row.table']),
                ('magpie', ['magpie/SecondIonizationEnergy.table']),
                ('magpie', ['magpie/ShearModulus.table']),
                ('magpie', ['magpie/SpaceGroupNumber.table']),
                ('magpie', ['magpie/SpecificHeatCapacity.table']),
                ('magpie', ['magpie/ThermalConductivity.table']),
                ('magpie', ['magpie/ThermalExpansionCoefficient.table']),
                ('magpie', ['magpie/ThirdIonizationEnergy.table']),
                ('magpie', ['magpie/valence.table'])],
    include_package_data = True,
    version=verstr,
    install_requires=[
        "aflow",
        "atomicwrites",
        "attrs>=17.4.0",
        "certifi==2018.4.16",
        "chardet==3.0.4",
        "citeproc-py>=0.4",
        "citrination-client==4.6.0",
        "configobj==5.0.6",
        "cryptography",
        "cycler==0.10.0",
        "Cython==0.29.13",
        "decorator==4.3.0",
        "dominate==2.3.5",
        "duecredit",
        "et_xmlfile",
        "forestci==0.3",
        "future>=0.16.0",
        "globus_nexus_client",
        "globus_sdk",
        "httplib2",
        "idna==2.7",
        "importlib-metadata>=0.12",
        "ipython-genutils==0.2.0",
        "jdcal",
        "jsonschema==2.6.0",
        "jupyter-core==4.4.0",
        "jwt",
        "keras==2.2.4",
        "kiwisolver==1.0.1",
        "matminer==0.5.5",
        "matplotlib==2.2.2",
        "mdf_forge>=0.6.1J",
        "mdf-toolbox>=0.4.7",
        "mlxtend==0.12.0",
        "monty==1.0.3",
        "more-itertools>=4.0.0",
        "mpmath==1.0.0",
        "nbformat==4.4.0",
        "networkx>=2.1",
        "nose==1.3.7",
        "numpy==1.16.2",
        "openpyxl",
        "packaging",
        "palettable==3.1.1",
        "pandas==0.24.2",
        "pint>=0.8.1",
        "plotly",
        "pluggy==0.12",
        "py>=1.5.0",
        "PyDispatcher==2.0.5",
        "pymatgen==2019.1.24",
        "pymongo>=3.6.1",
        "pyparsing==2.2.0",
        "pypif==2.1.0",
        "pytest==5.0.1",
        "python-dateutil==2.7.3",
        "pytz==2018.5",
        "pyyaml>=4.2b1",
        "requests==2.20.0",
        "retrying",
        "ruamel.yaml==0.15.42",
        "scikit-learn==0.20.3",
        "scikit-optimize==0.5.2",
        "scipy==1.2.1",
        "six==1.11.0",
        "spglib==1.10.3.65",
        "sympy==1.2",
        "tabulate==0.8.2",
        "tensorflow==1.13.1",
        "tqdm>=4.23.1",
        "traitlets==4.3.2",
        "urllib3>=1.24.2",
        "wcwidth",
        "xgboost",
        "xlrd",
        "zipp"],
    author="MAST Development Team, University of Wisconsin-Madison Computational Materials Group",
    author_email="ddmorgan@wisc.edu",
    url="https://github.com/uw-cmg/MAST-ML",
    license="MIT",
    description="MAterials Simulation Toolkit - Machine Learning",
    long_description="MAterials Simulation Toolkit for Machine Learning (MASTML)",
    keywords=["MAST","materials","simulation","MASTML","machine learning"],
)
