#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# MAterials Simulation Toolkit for Machine Learning (MAST-ML) documentation build configuration file, created by
# sphinx-quickstart on Mon Oct 22 14:47:26 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
#os.system('pip install sphinx-automodapi pandas scikit-learn dominate')
os.system('pip install sphinx-automodapi')
os.system('pip install citrination-client configobj dlhub_sdk dominate forestci globus_nexus_client globus_sdk keras matminer matplotlib mdf_forgemdf-toolbox mlxtend nbformat numpy pandas pymatgen scikit-learn scikit-optimize scipy sphinx-automodapi tensorflow urllib3 xlsxwriter')
#os.system('pip install aflow atomicwrites attrs>=17.4.0 certifi>=2020.12.05 chardet>=3.0.4 citeproc-py>=0.4 citrination-client>=6.5.1 configobj>=5.0.6 cryptography cycler>=0.10.0 Cython>=0.29.20 decorator>=4.4.1 dlhub_sdk>=0.9.4 dominate>=2.3.5 duecredit et_xmlfile folium>=0.2.1 forestci>=0.4.1 future>=0.18.2 globus_nexus_client globus_sdk httplib2 idna==2.7 imageio>=2.3.0 imgaug>=0.2.5 importlib-metadata>=0.12 ipython-genutils>=0.2.0 jdcal jsonschema>=3.0.2 jwt keras>=2.2.4 kiwisolver>=1.0.1 matminer>=0.5.5 matplotlib>=3.1.1 mdf_forge>=0.6.1J mdf-toolbox>=0.5.7 mlxtend>=0.17.2 monty>=1.0.2 nbformat networkx>=2.1 nose>=1.3.7 numpy==1.19.5 openpyxl packaging palettable>=3.1.1 pandas==1.1.5 pint>=0.8.1 plotly>=4.5.0 pluggy>=0.12 psutil>=5.5.1 py>=1.5.0 PyDispatcher>=2.0.5 pymatgen==2020.12.31 pymongo>=3.6.1 pyparsing>=2.2.0 pypif>=2.1.0 pytest>=5.0.1 python-dateutil>=2.7.3 pytz>=2018.5 pyyaml>=4.2b1 requests>=2.24.0 retrying ruamel.yaml>=0.15.42 scikit-learn==0.23.2 scikit-optimize>=0.5.2 scipy==1.5.4 six>=1.11.0 spglib>=1.10.3.65 sphinx-automodapi sympy>=1.2 tabulate>=0.8.2 tensorflow>=1.13.1 tqdm>=4.46.0 traitlets>=4.3.2 urllib3<1.25,>=1.24.2 wcwidth xlsxwriter>=1.3.7 xlrd zipp')
#os.system('pip install aflow atomicwrites attrs certifi chardet citeproc-py citrination-client configobj cryptography cycler Cython decorator dlhub_sdk dominate duecredit folium forestci future globus_nexus_client globus_sdk httplib2 idna imageio imgaug importlib-metadata ipython-genutils jdcal jsonschema jwt keras kiwisolver matminer matplotlib mdf_forge	mdf-toolbox mlxtend monty nbformat networkx nose numpy openpyxl packaging palettable pandas pint plotly pluggy psutil py PyDispatcher pymatgen pymongo pyparsing pypif pytest python-dateutil pytz pyyaml requests retrying	ruamel.yaml scikit-learn scikit-optimize scipy six spglib sphinx-automodapi sympy tabulate tensorflow tqdm traitlets urllib3 wcwidth xlrd xlsxwriter zipp')
#import sphinx_automodapi
sys.path.insert(0, os.path.abspath('../../'))
sys.path.insert(0, os.path.abspath('../../mastml'))
sys.path.insert(0, os.path.abspath('../../mastml/legos'))
#sys.path.insert(0, '/Users/ryanjacobs/PycharmProjects/MAST-ML/mastml/')
#sys.path.insert(0, '/Users/ryanjacobs/PycharmProjects/MAST-ML/mastml/legos')
# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.viewcode',
    'sphinx_automodapi.automodapi']

numpydoc_show_class_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'MAterials Simulation Toolkit for Machine Learning (MAST-ML)'
copyright = '2018, University of Wisconsin-Madison Computational Materials Group'
author = 'University of Wisconsin-Madison Computational Materials Group'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.0'
# The full version, including alpha/beta/rc tags.
release = '2.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'
#html_theme = 'classic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# Works for sphinx_rtd_theme
html_theme_options = {'collapse_navigation': False}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        #'about.html',
        #'navigation.html',
        #'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
        #'donate.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'MAterialsSimulationToolkitforMachineLearningMAST-MLdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'MAterialsSimulationToolkitforMachineLearningMAST-ML.tex', 'MAterials Simulation Toolkit for Machine Learning (MAST-ML) Documentation',
     'University of Wisconsin-Madison Computational Materials Group', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'mast', master_doc, 'materialssimulationtoolkitformachinelearningmast-ml', 'MAterials Simulation Toolkit for Machine Learning (MAST-ML) Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'MAterialsSimulationToolkitforMachineLearningMAST-ML', 'MAterials Simulation Toolkit for Machine Learning (MAST-ML) Documentation',
     author, 'MAterialsSimulationToolkitforMachineLearningMAST-ML', 'One line description of project.',
     'Miscellaneous'),
]



